### ISSUE TITLE
Support for Cloudfare captcha

### ISSUE THREAD

**Issue by diogovk** [Dwolla/dwolla-v2-python#23]
Hello. I work for Astra, one of your clients, and my office is in Brazil.

It seems Cloudfare requires captcha from Brazilian IP addresses.
I asked dwolla support for the whitelist of my IP address a few times, but since it's dynamic, I keep needing to ask over and over again.
![image](https://user-images.githubusercontent.com/225435/44302078-a9410580-a2f8-11e8-8bd2-11d3767f5854.png)

Is there a way I could solve the captcha once, and have the dwolla python library read that token/cookie from somewhere?

Please note that I only plan to access to sandbox environment from my IP, and I completely understand if keep being "strict" with IPs outside the USA for the production environment. That said being so strict with the sandbox doesn't make a lot of sense to me.

**Comment by spencerhunter** [comment]
Hi @diogovk , sorry for the inconvenience with needing to repeatedly whitelist your IP address. We're looking at solving this issue sometime this week so you shouldn't encounter these captchas when interacting with the dwolla site and API. Since it's not an issue of the python library itself, it's out of scope to make updates to solve for this particular issue. I'll send you a DM once this issue has been resolved.
